name: Lint Code

on:
  pull_request:
    branches: [ main, master, development ]
  push:
    branches: [ main, master, development ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
      
    - name: Check formatting
      run: npx prettier --config .prettierrc --check "src/**/*.{js,json,ts,css,scss,vue,html,md}" 